### ISSUE TITLE
ImageNet-1K adversarially pre-trained models

### ISSUE THREAD

**Issue by luniluni-chen** [GodXuxilie/ACL_Benchmark#1]
Excuse me, I notice that the link to ImageNet-1K adversarially pre-trained models in AutoLoRa does not exist. Can you provide other download methods?

**Comment by GodXuxilie** [comment]
Hi luniluni-chen,

it looks like the authors of [NeurIPS 2020 paper](https://proceedings.neurips.cc/paper/2020/file/24357dd085d2c4b1a88a7e0692e60294-Paper.pdf) has deactivated [their official GitHub](https://github.com/microsoft/robust-models-transfer). You can download the pre-trained ResNet-50 models from this [GitHub](https://github.com/MadryLab/robustness).

Please feel free to reach out to me if there is any further enquiry. Thank you! 

Best wishes,
Xilie

**Comment by luniluni-chen** [comment]
Ok, I forgot to check my email. Thanks for your reply!
        
    
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            XU ***@***.***>
            
        
      
      
        
         Date 
        
        
        12/20/2023 15:17
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [GodXuxilie/RobustSSL_Benchmark] ImageNet-1K adversarially pre-trained models (Issue #1)
        
      
    
  

Hi luniluni-chen,
it looks like the authors of NeurIPS 2020 paper has deactivated their official GitHub. You can download the pre-trained ResNet-50 models from this GitHub.
Please feel free to reach out to me if there is any further enquiry. Thank you!
Best wishes,
Xilie
